name       : iputils
version    : '20210722'
release    : 6
source     :
    - https://github.com/iputils/iputils/archive/refs/tags/20210722.tar.gz : 6d1a44b0682d3d4b64586dbaebe61dd61ae16d6e2f4dc0c43336d0e47a9db323
license    :
    - GPL-2.0-or-later
    - BSD-3-Clause
    - Rdisc
component  : network.utils
summary    : A set of small useful utilities for Linux networking.
description: |
    The iputils package is set of small useful utilities for Linux networking.
builddeps  :
    - pkgconfig(libgcrypt)
    - pkgconfig(libidn2)
    - docbook-xml
    - libcap2-devel
    - libxslt
setup      : |
    %apply_patches
    %meson_configure -DBUILD_TRACEROUTE6=true -DBUILD_RARPD=true
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Rename ping manpage
    mv $installdir/usr/share/man/man8/{,iputils-}ping.8
