name       : iputils
version    : '20221126'
release    : 8
source     :
    - https://github.com/iputils/iputils/archive/refs/tags/20221126.tar.gz : 745ea711fe06d5c57d470d21acce3c3ab866eb6afb69379a16c6d60b89bd4311
license    :
    - GPL-2.0-or-later
    - BSD-3-Clause
    - Rdisc
component  : network.utils
summary    : A set of small useful utilities for Linux networking.
description: |
    The iputils package is set of small useful utilities for Linux networking.
builddeps  :
    - pkgconfig(libgcrypt)
    - pkgconfig(libidn2)
    - docbook-xml
    - libcap2-devel
    - libxslt
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Rename ping manpage
    mv $installdir/usr/share/man/man8/{,iputils-}ping.8
