name       : iputils
version    : '20211215'
release    : 7
source     :
    - https://github.com/iputils/iputils/archive/refs/tags/20211215.tar.gz : b6f67fc705490673ff4471d006221b4a2f1b1180b929d9fefd771352621ccedf
license    :
    - GPL-2.0-or-later
    - BSD-3-Clause
    - Rdisc
component  : network.utils
summary    : A set of small useful utilities for Linux networking.
description: |
    The iputils package is set of small useful utilities for Linux networking.
builddeps  :
    - pkgconfig(libgcrypt)
    - pkgconfig(libidn2)
    - docbook-xml
    - libcap2-devel
    - libxslt
setup      : |
    %apply_patches
    %meson_configure -DBUILD_NINFOD=false -DBUILD_RARPD=false -DBUILD_RDISC=false
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Rename ping manpage
    mv $installdir/usr/share/man/man8/{,iputils-}ping.8
